# environment variable names
DDE_DOCUMENT_METADATA_TABLE_NAME = "DDE_DOCUMENT_METADATA_TABLE_NAME"
DDE_INPUT_LOCATION = "DDE_INPUT_LOCATION"
DDE_OUTPUT_LOCATION = "DDE_OUTPUT_LOCATION"
DDE_PROFILE_ARN = "DDE_PROFILE_ARN" 
DDE_PROJECT_ARN = "DDE_PROJECT_ARN"
DDE_REGION = "DDE_REGION"