# environment variable names
DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME = "DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME"
DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME = "DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME"
DOCUMENTAI_INPUT_LOCATION = "DOCUMENTAI_INPUT_LOCATION"
DOCUMENTAI_PREPROCESSING_LOCATION = "DOCUMENTAI_PREPROCESSING_LOCATION"
DOCUMENTAI_OUTPUT_LOCATION = "DOCUMENTAI_OUTPUT_LOCATION"
BDA_PROFILE_ARN = "BDA_PROFILE_ARN"
BDA_PROJECT_ARN = "BDA_PROJECT_ARN"
BDA_REGION = "BDA_REGION"
MAX_BDA_INVOKE_RETRY_ATTEMPTS = "MAX_BDA_INVOKE_RETRY_ATTEMPTS"
DOCUMENTAI_BATCH_TABLE_NAME = "DOCUMENTAI_BATCH_TABLE_NAME"
DOCUMENTAI_DOCUMENT_METADATA_BATCH_ID_INDEX_NAME = (
    "DOCUMENTAI_DOCUMENT_METADATA_BATCH_ID_INDEX_NAME"
)
DOCUMENTAI_MAX_BATCH_SIZE = "DOCUMENTAI_MAX_BATCH_SIZE"
