# environment variable names
DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME = "DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME"
DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME = "DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME"
DOCUMENTAI_INPUT_LOCATION = "DOCUMENTAI_INPUT_LOCATION"
DOCUMENTAI_OUTPUT_LOCATION = "DOCUMENTAI_OUTPUT_LOCATION"
DOCUMENTAI_PROFILE_ARN = "DOCUMENTAI_PROFILE_ARN"
DOCUMENTAI_PROJECT_ARN = "DOCUMENTAI_PROJECT_ARN"
DOCUMENTAI_REGION = "DOCUMENTAI_REGION"
