# environment variable names
API_AUTH_TOKEN = "API_AUTH_TOKEN"
DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME = "DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME"
DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME = "DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME"
DOCUMENTAI_INPUT_LOCATION = "DOCUMENTAI_INPUT_LOCATION"
DOCUMENTAI_OUTPUT_LOCATION = "DOCUMENTAI_OUTPUT_LOCATION"
BDA_PROFILE_ARN = "BDA_PROFILE_ARN"
BDA_PROJECT_ARN = "BDA_PROJECT_ARN"
BDA_REGION = "BDA_REGION"
