TEXTRACT_TO_BDA_FIELD_MAP = {
    "firstName": "NAME_DETAILS.FIRST_NAME",
    "middleName": "NAME_DETAILS.MIDDLE_NAME",
    "lastName": "NAME_DETAILS.LAST_NAME",
    "suffix": "NAME_DETAILS.SUFFIX",
    "address": "ADDRESS_DETAILS.STREET_ADDRESS",
    "city": "ADDRESS_DETAILS.CITY",
    "zipCode": "ADDRESS_DETAILS.ZIP_CODE",
    "state": "ADDRESS_DETAILS.STATE",
    "county": "COUNTY",
    "documentNumber": "ID_NUMBER",
    "expirationDate": "EXPIRATION_DATE",
    "dateOfBirth": "DATE_OF_BIRTH",
    "stateName": "STATE_NAME",
    "dateOfIssue": "DATE_OF_ISSUE",
    "licenseClass": "CLASS",
    "restrictions": "RESTRICTIONS",
    "endorsements": "ENDORSEMENTS",
    "sex": "PERSONAL_DETAILS.SEX",
}
